# Generated by Django 5.1.6 on 2025-02-15 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schdule", "0002_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="task",
        ),
    ]
