# Generated by Django 5.1.6 on 2025-02-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schdule", "0003_remove_message_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schdule.task",
            ),
        ),
    ]
