# Generated by Django 5.1.6 on 2025-02-17 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schdule", "0004_message_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="task",
        ),
    ]
